version: '2'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ${db}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:
    image: nextcloud
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_ADMIN_USER=${nextclouduser}
      - NEXTCLOUD_ADMIN_PASSWORD=${nextcloudpw}
      - NEXTCLOUD_DATA_DIR=/opt/nextcloud/data
      - NEXTCLOUD_TRUSTED_DOMAINS=${domain}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
    ports:
      - ${port}:80
    links:
      - db
    volumes:
      - ${nextcloud}:/var/www/html
      - ${nextclouddir}:/opt/nextcloud/data
      - ${apache}:/etc/apache2/sites-enabled
    restart: always
