version: '2'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ${vol_db}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:
    image: nextcloud
    ports:
      - ${port}:80
    links:
      - db
    volumes:
      - ${vol_nextcloud}:/var/www/html
    restart: always
